const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {

//╭──────────────────────Main──────────────────────╮//   
    SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMEF2WFBkaU8vQU1HNmc2Z2w2d0ltYWhnN0tmWUZ2ZEp2QWNpRlcwOW9Vaz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibE5ySStvWlFEWnFlY2dYZ2l6VFZ2bi8zQUJyZitPTFl2SzVKNGFIcTVCdz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJLSEJuajJxeWlja2tSSVVPelFHT29NS2xFYW54OGFKM3VuU2FkWkcrSVVvPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJuTkFXYmlLVERQeWg5TXZMSm90WklaanpVWFppdjZscUNVSHlWSkJRUGxNPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVIWUc5VDYwYWUwc1hBb042REhZRmpacDZnOUFzNVhWVWV2ZGZtdVpLV1U9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZMdW5qZnZ0TXl0ZHhyVjU3MFRzS0R1azBvVzdwZ2hoamMrK0V0ZEVGaUk9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUpwS3ZQbkxLbndFV0YySzdkOEsrM0RuMTA2WUNNMnFQbUJoU0U0ek0wTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUlTWGdkUjZGSDN2dy9lQng5UGdKdm94Tm5GQmgyck5RRHExSEZzWU0yZz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkxjNzZhbkFmem5mMjM0ZkN3RisvNEtzOGdtcSt6d0U0MHk1WVZvbEpvQk1HajdVeXVGTVB0NjZ3MytuUEkwWElKL1pQMUsxbnJkeHliU1lpMTdpWkJ3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTgsImFkdlNlY3JldEtleSI6InIybTJjSkhnaVYzMWRSNzJMSjNuRDNNenN6ZmtiWTBpeWlBZjlYdTVnS3M9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbXSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IlE0WmJtR192UnRtck5XZGlNSnJzcnciLCJwaG9uZUlkIjoiODg3MGM3N2EtN2VlNS00N2Q2LWJiODUtMjUxOTRmZmY2YWI0IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkRTTk5nT2ZKc2tuU1kyWEJzNzZ5THBPamlVWT0ifSwicmVnaXN0ZXJlZCI6ZmFsc2UsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieHNMNmZMNmhweUQ5c0g4YkdiTFBUMC9ibTVFPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDUEtaeHFNQkVQeXp5cmNHR0I4Z0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiZGVYaHZsSVRxVXVkVXYxa2NRMzFrMi9pbHBtU0VIbzVKcXNKejkwclFHcz0iLCJhY2NvdW50U2lnbmF0dXJlIjoiTEtZL1hLZTkyQUY3QktPRkROcklDbm4yNGZRWFRKSXFxMVFYYks5bGh4QTJRVG9DTVcrWFpUaFJrK09Dc05RVStDZXFlZWdOWm82dkI1cTdUbmo4Qnc9PSIsImRldmljZVNpZ25hdHVyZSI6IjJwRlhUclExVEVhT0xQU1JJOHJjNHJWYVQyOFJzOUdVdEI4SlA5ekMySkUyQkhQZ2FRaTgwL2JMMDdEeGZkcE5GUVVpZ3c0b3RDckdBZklhZUNwR0NRPT0ifSwibWUiOnsiaWQiOiI5NDc2NjQyODgzMjo1MUBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLwnZm0IPCdmbHwnZm+8J2ahyDwnZqC8J2ZuyJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5NDc2NjQyODgzMjo1MUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJYWGw0YjVTRTZsTG5WTDlaSEVOOVpOdjRwYVpraEI2T1NhckNjL2RLMEJyIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzI3MTc1MTc4LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUpJcSJ9",
    ALIVE_IMG: process.env.ALIVE_IMG || "https://telegra.ph/file/261c717e5e4f165712ec4.png",
    ALIVE_MSG: process.env.ALIVE_MSG || "Elix Is Alive Nox👍🇱🇰✅ ",
    AUTO_READ_STATUS: process.env.AUTO_READ_STATUS || "true",
    OWNER: process.env.OWNER || "Your Name",
    MODE: process.env.MODE || "public",
    OWNER_NUMBER: process.env.OWNER_NUMBER || "94763936166",
//╰────────────────────────────────────────────────╯//

//╭──────────────────────Auto──────────────────────╮//
    AUTO_REPLY: process.env.AUTO_REPLY || "true",
    AUTO_STICKER: process.env.AUTO_STICKER || "true",
    AUTO_VOICE: process.env.AUTO_VOICE || "true",
//╰────────────────────────────────────────────────╯//

    
};
